language: python
python:
- 3.6

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.ccache"

env:
  global:
  - secure: WlJkt8YmA6xu0SM7qTGOuresaEOHTWnDDZv3huNsowFxnjz/lnsNqttX3SRJP7uV1d+9kzsM1C1q5omN/6k3vlHr5HX+s+i1GKVSzPMzSau3Ez1BwcaC/8soxzHhw48E8hCfXNK7XVxCvz+ZgHP0zKEta+zEHk3bE7MNge6KqhkaWzyvtfh3qRAQ3vICAWOQUh9YLhKr5gc/oCndlf+e7Ky7qE3M8JSwYjJqbedQsv5qgp3SV9tdBsxR43RdRYfKQRcF1i2Q8wsQOKAXxkOAW4WQHAafKJVcRjmoGaKqXaHkDQhjoVSrEi8RQ1rrA4EgHeXqhHAyzhTvrNZL9e58Td+xS6Y3ZreiZ87uLbnhY0jfXAqWQ57xQNnO0wGaQlmv2dxyQjXiWMEnpL4WPU2IhkPTjwYbXSTel9n8ZqcpIr2ePwg+faXzei0AZCF2h5/SWOFXp6QDJj+azyYBXTGjFIdjLMy496J6HBhCPd0tNyksORM7KASQEqG/PRJFg1iauvqbqzeSWcNIInJNxVMnJAeRA3NdnQMLtOQNOvKtd9zgfaIUQEjnIBEgLvMiYsGT2/cNKSTlbLbBr1/poigA1m3BwGJiPV384zXBPmmI45UAONyZH58r2ZIwLYCuucLg8PfZekMbg/enGtay+MzZJu43sU67NbcPEqddWPICyYo=

install:
- set -eo pipefail
- pushd core/
- make all
- popd
- pip install .
- pip install -r requirements-dev.txt
#- python setup.py sdist bdist_wheel

# script:
# - coverage run -m pytest
# - coverage report -m
# - codecov
# - flake8 --max-line-length=115
# - set -e
# - make -C docs html
# - pip install doctr
# - doctr deploy --built-docs docs/build/html .

deploy:
  provider: pypi
  user: mrakitin
  password:
    secure: sugDJeduPToyZM/EH6sKC66lVMx4mF5ckzpRrrK6Ls15IIwp3PAweLcFfdHpzbqfHLpF346pN7epQPLHwa1QDwBRYs9tp1YbQBgY1/tiv7lF3Qw8dmAHWaGsvt77in+9LUAI5GdQ4pEHy+5gopibZBmcSXbvpcj2LFNaRjn5k9644GiXJ5zPSvhyg3jQMl1USxOJ22tG18yFhUAGjeh2EaX+zB5J2ZadXckV1A5zzMFO8Ec+Sd5Pe9at4aR568vqn9hl9UNBpxpMuM9s5p1avLen9GCsXdjOtB107vbEB8uIB6TchmZk3t58KwiiUAqdNkTq8ov+jupZMik4gQXlQvlXRLLbO5VS2imnyV5aYaYeuRSGNW3qtOvAqUGIsVm3sfLHOZDjTZUmJIkkpJhlEWlk2NR9PCSXdcJjahXBtGtU9CrnywmCyrqmNzZpzYqb5wmpM2ByNKblj7Y7nC7ojQb7Mhc9GCufECvsaVAKUIPBXllE/Z1JXC4PomvP4BIVDcyKuAkAGgAo2f3cjTTOr0z53LFPDf8kkFA0ePgLMSmmPKwN59L4C7liWqDWwIIbTlTuAtEZCtdmtUrGEp2ow3lrHK/gtudNlVPTNOmh7we6kSJQ4LDG+LI2lrHUbqbMmvdaM8+PNtrFquuMRqzavtn3LwkWq3U/KLsg2ZwMcgA=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
