language: python
python:
- 3.6
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.ccache"
env:
  global:
  - secure: WlJkt8YmA6xu0SM7qTGOuresaEOHTWnDDZv3huNsowFxnjz/lnsNqttX3SRJP7uV1d+9kzsM1C1q5omN/6k3vlHr5HX+s+i1GKVSzPMzSau3Ez1BwcaC/8soxzHhw48E8hCfXNK7XVxCvz+ZgHP0zKEta+zEHk3bE7MNge6KqhkaWzyvtfh3qRAQ3vICAWOQUh9YLhKr5gc/oCndlf+e7Ky7qE3M8JSwYjJqbedQsv5qgp3SV9tdBsxR43RdRYfKQRcF1i2Q8wsQOKAXxkOAW4WQHAafKJVcRjmoGaKqXaHkDQhjoVSrEi8RQ1rrA4EgHeXqhHAyzhTvrNZL9e58Td+xS6Y3ZreiZ87uLbnhY0jfXAqWQ57xQNnO0wGaQlmv2dxyQjXiWMEnpL4WPU2IhkPTjwYbXSTel9n8ZqcpIr2ePwg+faXzei0AZCF2h5/SWOFXp6QDJj+azyYBXTGjFIdjLMy496J6HBhCPd0tNyksORM7KASQEqG/PRJFg1iauvqbqzeSWcNIInJNxVMnJAeRA3NdnQMLtOQNOvKtd9zgfaIUQEjnIBEgLvMiYsGT2/cNKSTlbLbBr1/poigA1m3BwGJiPV384zXBPmmI45UAONyZH58r2ZIwLYCuucLg8PfZekMbg/enGtay+MzZJu43sU67NbcPEqddWPICyYo=
install:
- pip install -r requirements-dev.txt
- pushd core/
- make all
- popd
- python setup.py sdist bdist_wheel
- twine upload dist/*
# - pip install .
# - pip install -r requirements-dev.txt
deploy:
  provider: pypi
  user: mrakitin
  password:
    secure: nxLj2gpXcCXYHOM+XESaNl5i6NOESne/hkNxbT72AGehwpqWvSzJYIG3YG0WOmb3jsQ4/4q1nMvRSt8Jc6mBip+prlaTRTo8bkfIuvs53p9Yk5zB17sDi+ApUxGbHEscRNskg87S91BIB5YgwzN+pyDW4KM9PFUbN0yBxFKoiLH8TXDrOV/4GAfDdScuzjptJm7aKrxQ3YE49veMzebl2TDSIePmojpzHuFc7itvaGFVenPRK4Ib928jl+cFFoClhQ3T/Uz7eRBaTMNNUDeoCg4GAIX8N+CZr4UW1PyNvoSL5MCcVsR6ZyQ0P3TdGcEyYk1CYOTSEWCWKCMGy8V82p36l5PVCeFkmD/QgbuB9xZ+sRKBClDhVDkKZmwvpHOFGIF/Rs39XygHp3yLkMV76qav74d0Jd633GxJhFoMOrAKPJtqnxAbj1KlBhRy2rD4IuIYb870JJHgoDcu3d58AShDaQhKRbdfs/u9wfMzeMKZ2Keuvu5VAIXmp9i5nuyYlr9ieTggWfzPCDcFmnIATk6QtZMkTBDPa+Tmw/6sxd0HfQUuwa5tX4Md1+i6quaoxw+TflsXRP/v2Wgup9AEGKqdEzsDQ1fNY+25/EtteA1V8u/qck/3vSml/ZH5opTRcLshmpFQtQuBI479uOKCLTX6FvnztaA4JzpM13BIhc4=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
